In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15'}

rank = []
name = []
position = []
nation = []
age = []
team = []
value = []

for i in range(1,5):
    
    url = f"https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop?page={i}"

    r = requests.get(url, headers=headers)

    soup = BeautifulSoup(r.content, 'html.parser')

    player_info = soup.find_all('tr', class_=['odd', 'even'])

    for info in player_info:
        player = info.find_all("td")

        rank.append(player[0].text)
        name.append(player[3].text)
        position.append(player[4].text)
        age.append(player[5].text)
        nation.append(player[6].img['alt'])
        team.append(player[7].img['alt'])
        value.append(player[8].text.strip())

df = pd.DataFrame(
    {"rank": rank,
    "name": name,
    "position": position,
    "nation": nation,
    "age": age,
    "team": team,
    "value": value}
)
df

,rank,name,position,nation,age,team,value
0,1,Erling Haaland,Centre-Forward,Norway,24,Manchester City,€200.00m
1,2,Vinicius Junior,Left Winger,Brazil,24,Real Madrid,€200.00m
2,3,Lamine Yamal,Right Winger,Spain,17,FC Barcelona,€180.00m
3,4,Jude Bellingham,Attacking Midfield,England,21,Real Madrid,€180.00m
4,5,Kylian Mbappé,Centre-Forward,France,26,Real Madrid,€160.00m
...,...,...,...,...,...,...,...
95,96,Castello Lukeba,Centre-Back,France,22,RB Leipzig,€50.00m
96,97,Éderson,Central Midfield,Brazil,25,Atalanta BC,€50.00m
97,98,Oihan Sancet,Attacking Midfield,Spain,24,Athletic Bilbao,€50.00m
98,99,Gonçalo Ramos,Centre-Forward,Portugal,23,Paris Saint-Germain,€50.00m
99,100,Álex Baena,Left Winger,Spain,23,Villarreal CF,€50.00m

In [13]:
df.to_csv('MostValuePlayer_Top100.csv', index=False)